[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "~0.9.4"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true

