[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "~0.9.4"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "~2.2.4"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "~1.4.0"

[prune]
  go-tests = true
  unused-packages = true
